config/routes.rb
Sushi::Application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"
  get "about" => "pages#about" # creates a about_path
  get "contact" => "pages#contact"
  

  

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>"}, :default_url => "/images/:style/sushi.png"

  validates :image, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about  
  end

  def contact
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  
  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order(created_at: :desc).paginate(:page => params[:page], :per_page => 30)
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    # @pin = Pin.new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
      redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-inverse navbar-default" role="navigation">
  <!-- <div class="container"> -->
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to "Sushi", root_path, class: "navbar-brand" %>      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to root_path do%>
          <span class="glyphicon glyphicon-home"></span>Home
           <% end %> 
        </li>

        <li><%= link_to about_path do%>
          <span class="glyphicon glyphicon-heart"></span>About
          <% end %>  
        </li>

        <li><%= link_to contact_path do%>
          <span class="glyphicon glyphicon-envelope"></span>Contact
          <% end %>
        </li>

        <% if user_signed_in? %>
          <li><%= link_to new_pin_path do%>
            <span class="glyphicon glyphicon-plus"></span>New Pin
           <% end %> 
          </li>
          <li><%= link_to destroy_user_session_path, method: :delete do%>
            <span class="glyphicon glyphicon-off">Log-out
            <% end %>  
          </li>

          <li><%= link_to edit_user_registration_path do%>
            <span class="glyphicon glyphicon-cog"></span>Settings
            <% end %>
          </li>
         <% end %>   
      </ul>
    </div><!-- .navbar-collapse -->
  </div> <!-- container-fluid -->
  
</nav>


 







  <!-- <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link</a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sushi</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!-- Mobile first -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>
  <!-- render just means puts content of that partial here -->  
  <%= render 'layouts/header' %>	
	<div class= "container">
    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert alert-info")%>
    <% end %>

		<%= yield %>
	</div>	
</body>
</html>

app/views/pages/_home.html.erb
<!-- <div class ="jumbotron"> -->
<div class="container center">
	<h1>SUSHI AFICIONADOS</h1>
	<% if user_signed_in? %>
		#do something
	<% else %>
		<p>
			<%= link_to "Sign-In", new_user_session_path, class: "btn btn-default btn-circle" %>
			<%= link_to "Sign-Up", new_user_registration_path, class: "btn btn-primary btn-circle" %>
		</p>
	<% end %>	
</div>
<!-- </div> -->

app/views/pages/about.html.erb
<!-- <h1>About Us</h1>
<p></p> -->

<section id="about" class="container content-section text-center">
  <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
          <h2>About Sushi Aficionados</h2>
          <p>Sushi Aficionados is a visual guide to preparing and eating sushi</p>
          
          
      </div>
  </div>
</section>

app/views/pages/contact.html.erb
<section id="contact" class="container content-section text-center">
  <div class="row">
      <div class="col-lg-8 col-lg-offset-2">
          <h2>Contact Us</h2>
          <p>Feel free to email us to provide some feedback on our site, give us suggestions for new receipes and ideas, or to just say hello!</p>
          <p>feedback@sushi.com</p>
          <ul class="list-inline banner-social-buttons">
              <li><a href="https://twitter.com/kiy_Tang" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
              </li>
              <li><a href="https://github.com/kiytang"class="btn btn-default btn-lg"><i class="fa fa-github fa-fw"></i> <span class="network-name">Github</span></a>
              </li>
              <li><a href="https://plus.google.com/+KiyHongTang/posts" class="btn btn-default btn-lg"><i class="fa fa-google-plus fa-fw"></i> <span class="network-name">Google+</span></a>
              </li>
          </ul>
      </div>
  </div>
    </section>

app/views/pins/_form.html.erb
<%= form_for @pin, :html => { :multipart => true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.file_field :image, class: "form-control"%>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%=render "pages/home" unless user_signed_in? %>

<div id="masonry-pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
   <div class="box panel panel-default">
     <%= link_to image_tag(pin.image.url(:medium)), pin %>
     <div class="panel-body">
       <p><%= pin.description %></p>
       <p><%= pin.user.name if pin.user %></p>     
        <% if pin.user == current_user %>
          <div class="actions"> 
            <%= link_to edit_pin_path(pin) do%>
              <span class="glyphicon glyphicon-edit">Edit
            <% end %>  
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do%>
              <span class="glyphicon glyphicon-trash">Delete
            <% end %>
          </div><!-- actions -->
        <% end %>  
     </div><!-- panel body --> 
   </div><!-- panel panel-default"  -->
  <% end %>
</div>

<div class="center">
  <%= will_paginate @collection, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<div class="panel panel-default">
			<div class="panel-heading center">
				<%= image_tag @pin.image.url(:medium) %>
			</div><!-- panel-heading -->	
		<p id="notice"><%= notice %></p>

		<div class="panel-body">	
		  <p><%= @pin.description %></p>
		  <p><%= @pin.user.name if @pin.user %></p> 

		<% if @pin.user == current_user %>
			<%= link_to edit_pin_path(@pin) do%>
        <span class="glyphicon glyphicon-edit">Edit
      <% end %>  
		<% end %>
		</div>
	</div>	
</div><!-- row -->